version: '2'
services:
  cabin_db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spring_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
