version: '2'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spring_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password


  backend:
    image: nemchinovrp/spring-boot-security-jwt:0.0.3
    restart: always
    ports:
      - 8888:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/spring_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - docker-mysql
